name: Generate Language Stats

on:
  schedule:
    # Runs at 00:00 on the first day of every month
    - cron: "0 0 1 * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-language-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Language Stats
        uses: anuraghazra/github-readme-stats@master
        with:
          token: ${{ secrets.GH_PAT }}
          username: whatkindofmilkuare
          include_all_commits: true
          count_private: true
          custom_title: "My GitHub Language Stats"

      - name: Update README with stats
        run: |
          echo "![Language Stats](https://github-readme-stats.vercel.app/api/top-langs/?username=whatkindofmiluare&count_private=true)" >> README.md
